### PR TITLE
Run onResize callback before updating scrollbars

### PR DESCRIPTION
**Pull request by richvdh**

### CODE REVIEW

**Comment by richvdh** [comment]
@ara4n: This should make your forceUpdate() redundant

**Comment by ara4n** [comment]
I experimented with this change last night and it actually broke my fix 
in the main react-sdk PR...

**Comment by richvdh** [comment]
The reason this makes a difference appears to be related to text wrapping. For whatever reason, calling `update` first means that text has been rewrapped before the `onResize` callback happens, so `checkScroll` does the right thing. If `onResize` is called first, `checkScroll` sees the un-wrapped version of the text; the text is then rewrapped _after_ `checkScroll` runs, messing up the offset.

The question is, why does that make a difference, and can we come up with a more robust way of handling it? Apart from general unease about fragility, if geminipanel.update sees the un-wrapped text, it will lead to scrollbar-got-lost problems (https://github.com/vector-im/vector-web/issues/1216 etc)

**Comment by richvdh** [comment]
It looks like Chrome rewraps the text when `update` writes to `this._viewElement.style`.

**Comment by richvdh** [comment]
OH GOD I AM AN IDIOT

_obviously_ chrome hasn't reflowed the text before `update` has been called, because `update` is the thing that is responsible for doing the resizing of the element.

**Pull request closed without merging**
